### ISSUE TITLE
add the HUMAN enum to CallStatus

### ISSUE THREAD

**Issue by blaluc** [Nexmo/nexmo-java#147]

**Comment by cr0wst** [comment]
This was fixed in #191.

Prior to the 3.8.0 release we didn't have objects to handle the deserialization of the json payload sent to the `event_url` in various NCCO actions. Our documentation implies that the only way for a `human` status to occur is through the request sent to the `event_url`. Please feel free to re-open and correct me if I'm wrong.

The `com.nexmo.client.voice.CallStatus` enum was used with `CallEvent` created by `VoiceClient#createCall` and `CallInfo` created by `VoiceClient#listCalls`. It was never intended to be used for this purpose, but I understand where you're coming from because the name is used in two different parts of the API.

In #191 I created a separate package `com.nexmo.client.incoming` which has classes to achieve what, I think, you're trying to achieve.
