### ISSUE TITLE
The VerifyClient check method should also return verified phone number

### ISSUE THREAD

**Issue by andidev** [Nexmo/nexmo-java#151]
It should be possible to get the verified phone number from the VerifyClients check method result. This would make phone verification implementations easier for phone verification REST API's like this:

http://myapp.com/verify-phone-numner?phoneNumber=0702223313
```java
VerifyResult result = client.getVerifyClient().verify(TO_NUMBER, "NEXMO");
return result.getRequestId()
```

http://myapp.com/check-verification-code?requestId=&code=1234
```
CheckResult result = client.getVerifyClient().check(requestId, code);
userManagerService.updatePhoneNumber(SecurityContext.getCurrentUserId(), result.getVerifiedPhoneNumber());
```

**Comment by cr0wst** [comment]
Hi @andidev 

The response that we get back from the API does not contain the phone number.  In order to provide you with this information we would need the API, itself, to be updated.  I will pass this along to our engineering team.

As a workaround, you can use the `VerifyClient.search` method with the request id to retrieve the number. It would require an extra call:
```java
SearchResult result = client.getVerifyClient().search(requestId);
return result.getNumber();
```

Hope this helps!
