### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by ravin-d** [Nexmo/nexmo-java#176]
Hi, I'm a college student trying to work around Nexmo API to create something for a school project. I came across something which I could use some help with.

**import com.nexmo.client.verify.VerifyResult;**
My IDE is saying the following is deprecated and I should change it. What should I do in this instance? Is there an alternate class i can import that's an updated version?

**Comment by cr0wst** [comment]
Hi @ravin-d,

Sorry about this!

It was prematurely deprecated while switching our `VerifyClient` from the XML to the JSON endpoints because it won't be usable in the next major version (4.0.0) and will be replaced with `VerifyResponse`. However, right now it's the only option and is perfectly fine to use.

I have removed the deprecation in the `develop` branch and it will get pulled in with the next release which I'm planning for next week. I hope this clears up some of the confusion being caused. You're perfectly fine using it for now!

**Comment by ravin-d** [comment]
Hey @cr0wst ! Thanks so much for the clarification. Cheers.
