### ISSUE TITLE
Is it possible to check if an audio is being streamed into the call?

### ISSUE THREAD

**Issue by vinokanth92** [Nexmo/nexmo-java#243]
I want stream audio into an active call. But I do not want to stream while an audio is being currently streamed already. This is because when a new audio is stream while another streaming is in progress, the current streaming gets interrupted and the new streaming starts. 

I want to effectively know if there is streaming going on, so that I can schedule my streams accordingly.

I am looking for something like this
`if(!client.getVoiceClient().isStreaming(callId)) client.getVoiceClient().startStreaming(callId, url);`

**Comment by cr0wst** [comment]
Hi @vinokanth92. With the current capabilities of the Voice API available in the Java client it isn't possible to tell if audio is currently being streamed to the call.

However, we have a [Conversation API](https://developer.nexmo.com/conversation/overview) which is currently in Developer Preview that gives quite a bit more granularity when events occur. Namely, you can receive events when the audio has stopped playing.

You can use this service with your existing voice application, but it's going to take a bit of configuration as it uses version 2 of our [Application API](https://developer.nexmo.com/api/application.v2) which isn't available in the Java Client library yet.

Here's a general idea of how I was able to set it up so that I could get a notification when streamed audio wasn't available.

## Configure the Application

If you already have an existing Voice Application, you will need to add the `rtc` capability to it. This can be accomplished by using the endpoint outlined here: https://developer.nexmo.com/api/application.v2#updateApplication. The payload that you send it for configuration will need to include your existing voice webhooks, and an additional third endpoint for `rtc` events to be sent to.

Here's an example of what I sent it:

```json
{
    "name":"Conversation Testing",
    "capabilities":{
        "voice":{
            "webhooks":{
                "answer_url":{
                    "address":"https://cr0wst.ngrok.io/webhooks/answer",
                    "http_method":"GET"
                },
                "event_url":{
                    "address":"https://cr0wst.ngrok.io/webhooks/events",
                    "http_method":"GET"
                }
            }
        },
        "rtc":{
            "webhooks":{
                "event_url":{
                    "address":"https://cr0wst.ngrok.io/webhooks/rtc",
                    "http_method":"POST"
                }
            }
        }
    }
}
```

Once your application has been updated, you will be able to receive RTC events to your `rtc` webhook. One of these events is of type `audio.play:done`. You can see a list of possible events here: https://developer.nexmo.com/conversation/concepts/event

## Create a Webhook Endpoint

You'll get quite a few events to this endpoint during the course of the call, and the Conversation API hasn't been added to the Java Client Library yet (it's in progress at the moment), so you'll need to deserialize the JSON and determine the event yourself.

Here's an example of the event that comes in when audio finishes playing:

```json
{
    "application_id": "f48c25e0-6645-42e8-9b99-0ec0db54267c",
    "body": {
        "play_id": "7fc9f5df-2179-42ee-8da4-861880a562d9",
        "channel": {
            "id": "0a714fca-f848-4aeb-8bb5-8f2d53c95fc2",
            "type": "phone",
            "to": {
                "type": "phone",
                "number": "15555551234"
            },
            "from": {
                "type": "phone",
                "number": "Unknown"
            }
        }
    },
    "timestamp": "2019-04-12T16:07:05.766Z",
    "type": "audio:play:done"
}
```

I hope this helps! I realize it's a bit inconvenient at the moment because the functionality isn't in the Java Client Library, but it will be added soon and it will make deserializing that payload a bit easier.
