### ISSUE TITLE
VoiceName enum to have other fields like language, gender, SSML support

### ISSUE THREAD

**Issue by sharmasha2nk** [Nexmo/nexmo-java#284]
VoiceName enum to have other fields as per [documentation](https://developer.nexmo.com/voice/voice-api/guides/text-to-speech#voice-names). 
And supporting methods like `List<VoiceName> getVoiceNameByLanguage(String lang)`.

**Comment by sharmasha2nk** [comment]
Pull request added #285

**Comment by sharmasha2nk** [comment]
Hi @yallen011. There are multiple scenarios this would help. 
1.  We are working on AI-driven conversational IVR, which supports multiple languages. If we have this mapping in code, we can use it to provide voice name options to the client to choose from based on language and gender. 
2. We can also use it for randomly choosing the voice based on the language at runtime for a conversation session. Like 1st-time call might use Salli and next time when the user calls we use Joey. And we can filter at runtime what all Voices we can use based on language, gender, SSML support like I am doing in the new test case added.
3. Deprecating the voice names which are discontinued would help in identifying which are not to use now without referring the documentation.
4. All the info is in the code, so no need to go back and forth to code and doc.
5. Added missing Voice names like JOANNA, ADITI, etc.

I thought of using Locale instead of String for language, but that might be overdone and could be handled while filtering.

**Comment by yallen011** [comment]
@sharmasha2nk I apologize for the late response. I thought I had replied but I think it slipped through the cracks. Also, I would like to thank you very much for taking the time to explain your scenarios, Vonage team values your opinion. I have done some research around this in order to provide you with a  proper response, and based on earlier discussions around this topic, it was determined that the case for things like randomizing voices by languages and such were more of an edge case and would require much more overhead to change at this point. My best suggestion for your scenario would be to extend the Voicename class within your project to be able to add any capabilities and functionalities that you need for your project.
