### ISSUE TITLE
Disable https requirement via configuration

### ISSUE THREAD

**Issue by nbleisch** [Nexmo/nexmo-java#48]
right now, the nexmo client expects only a https endpoint which makes totally sense in the context of a production environment but is a bit costly when trying to use and configure a mock for testing purposes. 

Therefore, it would be really neat, if the client can by configured to use a plain http endpoint instead. This could be achieved by having an environment variable, system property or even an additional constructor argument or maybe make it implicit by directly checking the protocol in the given URI.

**Comment by stefanscheidt** [comment]
Another possible solution could be to replace the "throw new IllegalArgumentException" in the url check in LegacyClient Constructor with a "logger.warn ...".

**Comment by judy2k** [comment]
I'll give this some thought and see what we can do. I suspect it'll be an explicit 'opt-in' thing, as I don't want people to be able to do this without considering the risks.

**Comment by stefanscheidt** [comment]
Hi.

Are there any updates regarding making a service that uses the Nexmo Client testable?
The idea is to be able to have E2E tests for a service that uses the Nexmo Client and let the client talk with a mock of the Nexmo service. For this we need a possibility to set the URL(s) the client(s) should be talking to.

Or is there a different idea on how to test a service that uses the Nexmo Client library?

Regards
Stefan

**Comment by judy2k** [comment]
Hi @stefanscheidt 

I think the problem here is that you're trying to mock the underlying HTTP service instead of the Nexmo Client library. The Nexmo Client Library has already been tested with the Nexmo API, to ensure that, when called properly, it creates the correct requests and response objects.

A better approach for your tests would be to mock the `NexmoClient` object (or `InsightClient` or whatever specific client you're using). In this way, you won't be generating any actual HTTP(S) requests, but you can verify that you're passing in the values you expect to the Nexmo Client methods you're calling.

Does that help?

**Comment by stefanscheidt** [comment]
Hi @judy2k,

thanks for your reply. Your approach is a good idea and we already do exactly that for our unit tests. But we also do End-to-End-tests of our service and in this case we would like to test the service "as is". And then we would like to talk to a mocked Nexmo Service.

Kind Regards.
Stefan

**Comment by judy2k** [comment]
So v2 of the library doesn't *currently* support changing the baseUrl at all, because I didn't have time to implement and test it. *But* it is on the list of things to implement. I've just opened #58 for this.

When I do implement it, I'll allow http URLs, because users will only be changing this value for testing anyway (*our* primary use case is testing the library against development versions of the Nexmo API)

If you're awaiting this change, I'd prepare to move to v2 of the library, and watch #58 for notifications of this feature. In the meantime, I'm going to close this thread as resolved.

**Comment by stefanscheidt** [comment]
Great news. Thanks!
