### ISSUE TITLE
missing special characters in sms

### ISSUE THREAD

**Issue by parapunzi** [Nexmo/nexmo-java#60]
using 2.0.1 when sending a unicode SMS message, e.g.

`new NexmoClient().getSmsClient().submitMessage(new TextMessage(from, to, "text with umlaut öäü", true))`

I don't see those special charactes in the SMS -- and logs show that HttpClient is POST-ing with header

> Content-Type: application/x-www-form-urlencoded; charset=ISO-8859-1

**Comment by judy2k** [comment]
Hi @parapunzi - sorry for the delay getting back to you. We'll aim to reproduce this week, and hopefully fix. We'll let you know what we find.

**Comment by parapunzi** [comment]
thanks - btw. I had temporarily to revert to nexmo client client-2.0.0-20170220.120052-2.jar because the httpclient 4.5 library in 2.0.1 conflicts with resteasy on jboss 6.4 (see https://bugzilla.redhat.com/show_bug.cgi?id=1266122).
And found out that when using the older client lib together with httpclient 4.3.6 the umlauts work..

**Comment by judy2k** [comment]
@parapunzi The bug is with the HttpClient's RequestBuilder class, and the bug still exists in 4.3.6. In the 2.0.0 snapshot release we weren't using RequestBuilder for the SMS calls, so the bug isn't there. Unfortunately, moving to RequestBuilder has introduced the problem.

I've fixed it in #62 which is undergoing review, but it's not going to solve your jboss compatibility problem.

**Comment by judy2k** [comment]
This problem's been fixed in the new 2.0.2 release.

@parapunzi Thank you for reporting this bug so we could fix it!
